### ISSUE TITLE
Authenticate does not work for Proxy routes 

### ISSUE THREAD

**Issue by sam-masscreations** [Shopify/shopify-app-template-remix#305] opened 2023-08-14 17:17 UTC
Proxy route unable to authenticate request and redirects to /auth/login. this same request works fine in the app backend.

```
export async function loader({request}) {
  const {admin} = await shopify.authenticate.admin(request);

  const response = await admin.graphql(
    `#graphql
    mutation populateProduct($input: ProductInput!) {
      productCreate(input: $input) {
        product {
          id
        }
      }
    }`,
    {
      variables: {
        input: {
          title: 'New product',
          variants: [{price: 100}],
        },
      },
    },
  );
  const parsedResponse = await response.json(); 

  return json({data: parsedResponse});
}

export default function AdditionalPage() {
  return (  
    <div>
      hello
    </div>
  );
}
```

**Comment by byrichardpowell** [comment] 2023-08-16 15:49
Thanks for opening an issue.

I'm going to close this issue as we think it's a duplicate of https://github.com/Shopify/shopify-app-template-remix/issues/295.

We want to make this a priority.  So stay tuned.

**Closed by byrichardpowell** 2023-08-16 15:49 UTC
