### ISSUE TITLE
Navigating in the side nav doesn't highlight the menu item on first click

### ISSUE THREAD

**Issue by owlyowl** [Shopify/shopify-app-template-remix#460] opened 2023-12-20 04:06 UTC
# Issue summary

In the sample app as well as in further app development, clicking on child menu items doesn't highlight the item in the grey sidebar on first click, it requires a 2nd click to engage the active state:
e.g.
https://github.com/Shopify/shopify-app-template-remix/blob/main/app/routes/app.tsx#L26

@shopify/shopify-app-remix version: 2.0.2
Node version: 18
Operating system: Windows 11

## Expected behavior

Clicking on a child nav item causes it to appear in the active/highlighted state

## Actual behavior

It requires a second click to have the menu update to highlighted

## Steps to reproduce the problem

1. Install sample app
2. Click on "Additional Page"
3. Observe "Additional Page" menu item is not highlighted on first click

**Comment by lizkenyon** [comment] 2023-12-20 17:32
Hi there 👋 

I am going to close this as a duplicate of #369 

This is an issue with App Bridge, and we have forwarded it to that team, but a community member has come up with a [workaround](https://github.com/Shopify/shopify-app-template-remix/issues/369#issuecomment-1759303079) in that thread that you may want to review.

**Closed by lizkenyon** 2023-12-20 17:32 UTC
