### ISSUE TITLE
[ERROR] Could not resolve react / react-dom / etc... 

### ISSUE THREAD

**Issue by xstortionist** [Shopify/shopify-app-template-remix#415] opened 2023-11-03 16:55 UTC
# Issue summary

Not able to use any dependencies that import React with the typescript remix template. I've tried a number of workarounds to no prevail. Any suggestions on how to avoid these errors when working with other packages? Could simply be related to WSL as that's generally the case, however wasn't able to identify any related issues that provided a solution.

- `@shopify/shopify-app-remix` version: ^2.0.2
- Node version: v18.18.2
- Operating system: Windows 11 (WSL)

```
12:40:30 │ remix    │  💿  remix dev
12:40:30 │ remix    │ 
12:40:30 │ remix    │  info  building...
12:40:31 │ webhooks │ Sending APP_UNINSTALLED webhook to app server
12:40:31 │ remix    │ ✘ [ERROR] Could not resolve "react"
12:40:31 │ remix    │ 
12:40:31 │ remix    │     ../node_modules/[dependency]/react/dist/index.js:1:150:
12:40:31 │ remix    │       1 │ ...as C, memo as A, useMemo as Ne, createElement as Ve } from "react";
12:40:31 │ remix    │         ╵                                                               ~~~~~~~
12:40:31 │ remix    │ 
12:40:31 │ remix    │   You can mark the path "react" as external to exclude it from the bundle, which will remove this error.
12:40:31 │ remix    │ 
12:40:31 │ remix    │ 
12:40:31 │ remix    │ ✘ [ERROR] Could not resolve "react-dom"
12:40:31 │ remix    │ 
12:40:31 │ remix    │     ../node_modules/[dependency]/react/dist/index.js:2:35:
12:40:31 │ remix    │       2 │ import { createPortal as Tt } from "react-dom";
12:40:31 │ remix    │         ╵                                    ~~~~~~~~~~~
12:40:31 │ remix    │ 
12:40:31 │ remix    │   You can mark the path "react-dom" as external to exclude it from the bundle, which will remove this error.
```

## Expected behavior

Dev environment launches without error.

## Actual behavior

Get presented with could not resolve error, resulting in an unresponsive app.

## Steps to reproduce the problem

1. Install dependency that imports react
2. Command: npm run dev -- --reset --tunnel-url https://.....ngrok-free.app:[port # her]

**Comment by paulomarg** [comment] 2023-11-13 19:34
Hi! Based on the error messages, this seems to happen when the remix server starts, but that is working normally. It sounds like the issue is either happening while installing the dependencies, or it's related to WSL as you mentioned.

Unfortunately, we wouldn't be able to solve either of those cases from this repo, so there's not a lot that we can do.

Since we can't action this, I'm going to close the issue. If you manage to track it down to something added by our template or packages, please do open a new issue and we'll fix it!

**Closed as completed by paulomarg** 2023-11-13 19:34 UTC
