### ISSUE TITLE
401 error after installation

### ISSUE THREAD

**Issue by marsan957** [Shopify/shopify-app-template-remix#286] opened 2023-08-04 07:25 UTC
I am facing an issue with the Shopify CLI and Node.js app template (Remix) where, after running the commands, I receive a 401 status code and the app does not load. Strangely, it was working fine yesterday, and no changes have been made since then.

 

Also tried to create a new app and same issue, any ideas?

 

To recreate the issue, you can follow these steps:

https://shopify.dev/docs/apps/getting-started/create

**Comment by meandillar** [comment] 2023-08-06 23:39
I'm having a similar problem after creating a new app. It tries to authenticate 3 times before failing with 401 and shows "same site cookies" error. Tried both chrome and firefox, cleared cookies, all with same result.

@marsan957 unrelated to the initial problem with your app not loading - when you tried creating a new app did you uninstall the existing one and recreate it with the same name? I was able to work around the problem by naming the app differently on a fresh install. I found that even after uninstalling the app from the dev store, deleting it from the partners dashboard and deleting all browser cookies, creating an app with the same name would result in the 401 error. I have also experienced this behaviour attempting to migrate an existing express app to the new remix format.

**Comment by alessandrome** [comment] 2023-08-12 18:13
I had the same problem here: I've to delete the old session row from Prisma db and then oauth result in a normal 200 OK response, but now nothing is shown on the default example app page 
![image](https://github.com/Shopify/shopify-app-template-remix/assets/25536870/f2172050-8456-4ebb-92bc-1702bd8e59db)

**Comment by meandillar** [comment] 2023-08-15 02:07
After a few days with no issues I randomly encountered the problem again. Tried to deploy app and push config. Added the debugging that you suggested @paulomarg . Here's an excerpt of what I get (prints this 2 or 3 times over):

```
Authenticating admin request
[shopify-app/INFO] Handling OAuth begin request
[shopify-app/DEBUG] OAuth request contained valid shop | {shop: redacted.myshopify.com}
[shopify-api/INFO] Beginning OAuth | {shop: redacted.myshopify.com, isOnline: false, callbackPath: /auth/callback}
[shopify-api/DEBUG] OAuth started, redirecting to https://redacted.myshopify.com/admin/oauth/authorize?client_id=d10c54f0d45b1829a04f6bb0c7c538e8&scope=write_products%2Cwrite_cart_transforms%2
Cwrite_discounts&redirect_uri=https%3A%2F%2Fsome-random-name.trycloudflare.com%2Fauth%2Fcallback&state=257910266455250&grant_options%5B%5D= | {shop: redacted.myshopify.com, isOnline: false}
GET /auth?shop=redacted.myshopify.com 302 - - 7.715 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/INFO] Handling OAuth callback request
[shopify-api/INFO] Completing OAuth | {shop: redacted.myshopify.com}
[shopify-api/DEBUG] OAuth request is valid, requesting access token | {shop: redacted.myshopify.com}
[shopify-api/INFO] Creating new session | {shop: redacted.myshopify.com, isOnline: false}
[shopify-app/INFO] Running afterAuth hook
[shopify-api/INFO] Registering webhooks | {shop: redacted.myshopify.com}
GET /auth/callback?code=c6923f9d35255a2e7ad2215328975f38&hmac=aa90cd6249b98a067a7d508fdd363bc95dc1c70d04a2b5f8f9ce28a83de86631&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&shop=sprtsfl-ap
ps.myshopify.com&state=257910266455250&timestamp=1692064959 302 - - 435.155 ms
[shopify-api/DEBUG] Existing topics: [APP_UNINSTALLED] | {shop: redacted.myshopify.com}
GET /?embedded=1&hmac=7709691092d843c849f84cb756086fc6371bc8c3238b0d7355c73ccd755a3a27&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367f7ad76e29c89cf1f9a
ec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961 302 - - 1.964 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Ensuring app is installed on shop | {shop: redacted.myshopify.com}
[shopify-app/DEBUG] Missing session token in search params, going to bounce page | {shop: redacted.myshopify.com}
GET /app?embedded=1&hmac=7709691092d843c849f84cb756086fc6371bc8c3238b0d7355c73ccd755a3a27&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367f7ad76e29c89cf1
f9aec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961 302 - - 4.211 ms
GET /?embedded=1&hmac=5dc078ad0abc2cd31d7586f0ddc0d56d43551dba3e5a113d084b4c42a9bdb488&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&session=71367f7ad76e29c89cf1f9aec636580c45
94067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961 302 - - 1.740 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Rendering bounce page
GET /auth/session-token?embedded=1&hmac=7709691092d843c849f84cb756086fc6371bc8c3238b0d7355c73ccd755a3a27&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367
f7ad76e29c89cf1f9aec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961&shopify-reload=https%3A%2F%2Fsome-random-name.trycloudflare.com%2Fapp%3Fembedded%3
D1%26hmac%3D7709691092d843c849f84cb756086fc6371bc8c3238b0d7355c73ccd755a3a27%26host%3DYWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz%26locale%3Den-NZ%26prefetch%3D1%26session%3D71367f7ad76e29c89cf1f9aec636580c4594067b2
14883660f79469f273ccb3b%26shop%3Dredacted.myshopify.com%26timestamp%3D1692064961 200 - - 2.176 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Ensuring app is installed on shop | {shop: redacted.myshopify.com}
[shopify-app/DEBUG] Missing session token in search params, going to bounce page | {shop: redacted.myshopify.com}
GET /app?embedded=1&hmac=5dc078ad0abc2cd31d7586f0ddc0d56d43551dba3e5a113d084b4c42a9bdb488&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&session=71367f7ad76e29c89cf1f9aec636580
c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961 302 - - 6.162 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Rendering bounce page
GET /auth/session-token?embedded=1&hmac=5dc078ad0abc2cd31d7586f0ddc0d56d43551dba3e5a113d084b4c42a9bdb488&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&session=71367f7ad76e29c8
9cf1f9aec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961&shopify-reload=https%3A%2F%2Fsome-random-name.trycloudflare.com%2Fapp%3Fembedded%3D1%26hmac%3
D5dc078ad0abc2cd31d7586f0ddc0d56d43551dba3e5a113d084b4c42a9bdb488%26host%3DYWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz%26locale%3Den-NZ%26session%3D71367f7ad76e29c89cf1f9aec636580c4594067b214883660f79469f273ccb3b%26
shop%3Dredacted.myshopify.com%26timestamp%3D1692064961 200 - - 2.259 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Validating session token
[shopify-app/DEBUG] Session token is valid | {payload: {"iss":"https://redacted.myshopify.com/admin","dest":"https://redacted.myshopify.com","aud":"d10c54f0d45b1829a04f6bb0c7c538e8","sub":
"44531974276","exp":1692065022,"nbf":1692064962,"iat":1692064962,"jti":"5e69526a-b59a-4665-aece-48a714e85def","sid":"184c0b284c4ae2e455ce91cd9e519e1a2b09a086b449c82557c947b764ecf9d6"}}
[shopify-app/DEBUG] Loading session from storage | {sessionId: offline_redacted.myshopify.com}
[shopify-app/DEBUG] Found a session, but it has expired, redirecting to OAuth | {shop: redacted.myshopify.com}
GET /app?embedded=1&hmac=5dc078ad0abc2cd31d7586f0ddc0d56d43551dba3e5a113d084b4c42a9bdb488&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&session=71367f7ad76e29c89cf1f9aec636580
c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064961 401 - - 9.670 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/INFO] Handling OAuth begin request
[shopify-app/DEBUG] OAuth request contained valid shop | {shop: redacted.myshopify.com}
[shopify-api/INFO] Beginning OAuth | {shop: redacted.myshopify.com, isOnline: false, callbackPath: /auth/callback}
[shopify-api/DEBUG] OAuth started, redirecting to https://redacted.myshopify.com/admin/oauth/authorize?client_id=d10c54f0d45b1829a04f6bb0c7c538e8&scope=write_products%2Cwrite_cart_transforms%2
Cwrite_discounts&redirect_uri=https%3A%2F%2Fsome-random-name.trycloudflare.com%2Fauth%2Fcallback&state=236601075483873&grant_options%5B%5D= | {shop: redacted.myshopify.com, isOnline: false}
GET /auth?shop=redacted.myshopify.com 302 - - 6.466 ms
GET /?embedded=1&hmac=14047e5cac4584abe5c5a16b269147018936a67644a1534aed63d6edfcfab938&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367f7ad76e29c89cf1f9a
ec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064966 302 - - 1.420 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Ensuring app is installed on shop | {shop: redacted.myshopify.com}
[shopify-app/DEBUG] Missing session token in search params, going to bounce page | {shop: redacted.myshopify.com}
GET /app?embedded=1&hmac=14047e5cac4584abe5c5a16b269147018936a67644a1534aed63d6edfcfab938&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367f7ad76e29c89cf1
f9aec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064966 302 - - 6.254 ms
[shopify-app/INFO] Authenticating admin request
[shopify-app/DEBUG] Rendering bounce page
GET /auth/session-token?embedded=1&hmac=14047e5cac4584abe5c5a16b269147018936a67644a1534aed63d6edfcfab938&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz&locale=en-NZ&prefetch=1&session=71367
f7ad76e29c89cf1f9aec636580c4594067b214883660f79469f273ccb3b&shop=redacted.myshopify.com&timestamp=1692064966&shopify-reload=https%3A%2F%2Fsome-random-name.trycloudflare.com%2Fapp%3Fembedded%3
D1%26hmac%3D14047e5cac4584abe5c5a16b269147018936a67644a1534aed63d6edfcfab938%26host%3DYWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc3BydHNmbC1hcHBz%26locale%3Den-NZ%26prefetch%3D1%26session%3D71367f7ad76e29c89cf1f9aec636580c4594067b2
14883660f79469f273ccb3b%26shop%3Dredacted.myshopify.com%26timestamp%3D1692064966 200 - - 4.260 ms
```

**Comment by mg-takuma-katanosaka** [comment] 2023-08-28 09:45
I encountered similar this problem.
We must update "SCOPE" environment variable if use this one when modified OAuth' scope in our Shopify App.
But I lacked an operation that updated it. So my app had been happening redirect loop and unauthorizing on Shopify.
I fix this problem to update the "SCOPE" variable to same value defining in `shopify.app.toml`.

Hope this helps.
Regards,

**Comment by TheRealFlyingCoder** [comment] 2023-08-31 23:10
Just coming here to add, I also was bitten by this mismatching scopes issue for hours.

You have to update scopes in 3 separate locations, which is a recipe for problems like this

At a bare minimum there should be a dev log somewhere in the code that warns "Expected SCOPES: ___, but received SCOPES: ___, please check your runtime variables are up to date with the App config, and synced with your Shopify project"

Ideally we'd discard the need for scope management in the runtime variables. Clearly the instantiation knows what Scopes are set on Shopify, otherwise it wouldn't throw the error, so why do we need to pass in SCOPES at runtime at all?

**Comment by paulomarg** [comment] 2023-09-01 13:10
Hi folks, thanks for all of your feedback, we really appreciate it.

I've escalated this issue with the team, and we're investigating ways to improve the experience around updating scopes so that it doesn't fall on the developer to remember to update them in multiple places.

I'll get back to you as soon as we have news to share, but in the meantime please remember to run `config:link` and `config:push` when you change your `web.toml` file to ensure all of the changes are in sync before you run the app.

Thank you for your patience!

**Comment by rosnelarguelloarh** [comment] 2023-09-12 05:03
I was able to resolve this login error by accessing the authentication URL directly in my browser: YourURL.trycloudflare.com/auth/shopify/callback. I logged in using the store's URL. I had been struggling with this issue for a couple of days.

**Comment by LHongy** [comment] 2023-09-27 03:17
Do you have two environment running the same app?
For example, both the local and testing environment using the same Shopify app.
I ran into this problem as well, and then I create another app for testing environment
It seems the issue is gone, I am not sure if that was the fix though.

**Comment by duncan-fairley** [comment] 2023-10-01 04:33
I ran into this issue after changing scopes in my `shopify.app.toml` file. 

It turns out if you're using the Remix template with Prisma you also need to update your existing session in Prisma to match. 

After running `npm run prisma studio` I was able to log into the Prisma visual UI and update the session on my local machine. After this the 401 disappeared. 

<img width="1624" alt="Screenshot 2023-09-30 at 9 29 55 PM" src="https://github.com/Shopify/shopify-app-template-remix/assets/995071/39e18f38-03f7-435f-974b-d522a49cd714">

**Comment by AlexGouget** [comment] 2023-10-17 11:51
I have the same issue, 

 [shopify-app/INFO] Authenticating admin request
13:44:28 │ remix    │ [shopify-app/INFO] Authenticating admin request                                                                                                                                                               
13:44:28 │ remix    │ ErrorResponseImpl {                                                                                                                                                                                           
13:44:28 │ remix    │   status: 401,                                                                                                                                                                                                
13:44:28 │ remix    │   statusText: 'Unauthorized',                                                                                                                                                                                 
13:44:28 │ remix    │   internal: false,                                                                                                                                                                                            
13:44:28 │ remix    │   data: ''                                                                                                                                                                                                    
13:44:28 │ remix    │ }
13:44:28 │ remix    │ ErrorResponseImpl {
13:44:28 │ remix    │   status: 401,
13:44:28 │ remix    │   statusText: 'Unauthorized',
13:44:28 │ remix    │   internal: false,
13:44:28 │ remix    │ }
13:44:28 │ remix    │ ErrorResponseImpl {
13:44:28 │ remix    │   status: 401,
13:44:28 │ remix    │   statusText: 'Unauthorized',
13:44:28 │ remix    │   internal: false,
13:44:28 │ remix    │   data: ''
13:44:28 │ remix    │ }

**Comment by horst7000** [comment] 2023-10-18 08:29
I only saw a "handling response" message in the admin view when launching my app in the dev store. I was able to resolve the issue by manually synchronizing my device clock in the Windows date and time settings. This problem occurs every other week again. Hope this might help someone.

**Comment by DanojaDias** [comment] 2023-10-20 15:50
I also face the same issue. Tried config:link and config:push and almost everything above. But still getting the issue. I added the debug logs as described by @paulomarg. 
`21:06:42 │ remix │ GET /?embedded=1&hmac=014a6630e48430b0d8759de528fb540d366b60d4f7eabadbdb9f83eeb9a23806&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816225 302 - - 8.232 ms
21:06:43 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:43 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:43 │ remix │ [shopify-app/DEBUG] Ensuring app is installed on shop | {shop: new-danoja.myshopify.com}
21:06:43 │ remix │ [shopify-app/DEBUG] Ensuring app is installed on shop | {shop: new-danoja.myshopify.com}
21:06:44 │ remix │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:
new-danoja.myshopify.com}
21:06:44 │ remix │ [shopify-app/INFO] Shop hasn't installed app yet, redirecting to OAuth | {shop:
new-danoja.myshopify.com}
21:06:44 │ remix │ GET /app?embedded=1&hmac=014a6630e48430b0d8759de528fb540d366b60d4f7eabadbdb9f83eeb9a23806&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816225 302 - - 1335.774 ms
21:06:45 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:46 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:46 │ remix │ [shopify-app/INFO] Handling OAuth begin request
21:06:46 │ remix │ [shopify-app/DEBUG] OAuth request contained valid shop | {shop: new-danoja.myshopify.com}
21:06:46 │ remix │ [shopify-api/INFO] Beginning OAuth | {shop: new-danoja.myshopify.com, isOnline: false, callbackPath:
/auth/callback}
21:06:49 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:49 │ remix │ [shopify-app/INFO] Handling OAuth callback request
21:06:49 │ remix │ [shopify-api/INFO] Completing OAuth | {shop: new-danoja.myshopify.com}
21:06:49 │ remix │ [shopify-api/DEBUG] OAuth request is valid, requesting access token | {shop:
new-danoja.myshopify.com}
21:06:49 │ remix │ [shopify-api/INFO] Creating new session | {shop: new-danoja.myshopify.com, isOnline: false}
21:06:49 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:49 │ remix │ [shopify-app/DEBUG] Rendering exit iframe page | {destination: /auth?shop=new-danoja.myshopify.com}
21:06:49 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:49 │ remix │ [shopify-app/DEBUG] Rendering exit iframe page | {destination: /auth?shop=new-danoja.myshopify.com}
21:06:49 │ remix │ GET /auth/exit-iframe?embedded=1&hmac=014a6630e48430b0d8759de528fb540d366b60d4f7eabadbdb9f83eeb9a23806&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816225&exitIframe=%2Fauth%3Fshop%3Dnew-danoja.myshopify.com 200 - - 2.626 ms
21:06:49 │ remix │ GET /auth/exit-iframe?embedded=1&hmac=014a6630e48430b0d8759de528fb540d366b60d4f7eabadbdb9f83eeb9a23806&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816225&exitIframe=%2Fauth%3Fshop%3Dnew-danoja.myshopify.com 200 - - 3.741 ms
21:06:50 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:50 │ remix │ [shopify-app/DEBUG] Rendering exit iframe page | {destination: /auth?shop=new-danoja.myshopify.com}
21:06:50 │ remix │ GET /auth/exit-iframe?embedded=1&hmac=014a6630e48430b0d8759de528fb540d366b60d4f7eabadbdb9f83eeb9a23806&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816225&exitIframe=%2Fauth%3Fshop%3Dnew-danoja.myshopify.com21:06:51 │ remix │ [shopify-app/DEBUG] Registered webhook | {topic: APP_UNINSTALLED, shop: new-danoja.myshopify.com,
operation: create}
21:06:54 │ remix │ GET /?embedded=1&hmac=e0dfa7a212d0fcebe48fed612bf046cfd8aa87fad48b6ac315f2a9c6e2497ead&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816238 302 - - 4.893 ms
21:06:55 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:55 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:55 │ remix │ [shopify-app/DEBUG] Ensuring app is installed on shop | {shop: new-danoja.myshopify.com}
21:06:55 │ remix │ [shopify-app/DEBUG] Ensuring app is installed on shop | {shop: new-danoja.myshopify.com}
21:06:55 │ remix │ [shopify-app/DEBUG] Missing session token in search params, going to bounce page | {shop:
new-danoja.myshopify.com}
21:06:55 │ remix │ [shopify-app/DEBUG] Missing session token in search params, going to bounce page | {shop:
new-danoja.myshopify.com}
21:06:55 │ remix │ GET /app?embedded=1&hmac=e0dfa7a212d0fcebe48fed612bf046cfd8aa87fad48b6ac315f2a9c6e2497ead&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816238 302 - - 149.381 ms
21:06:55 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:55 │ remix │ [shopify-app/DEBUG] Rendering bounce page
21:06:55 │ remix │ GET /auth/session-token?embedded=1&hmac=e0dfa7a212d0fcebe48fed612bf046cfd8aa87fad48b6ac315f2a9c6e2497ead&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816238&shopify-reload=https%3A%2F%2Felect-ipaq-brooks-luck.trycloudflare.com%2Fapp%3Fembedded%3D1%26hmac%3De0dfa7a212d0fcebe48fed612bf046cfd8aa87fad48b6ac315f2a9c6e2497ead%26hos21:06:56 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:56 │ remix │ [shopify-app/DEBUG] Validating session token
21:06:56 │ remix │ [shopify-app/INFO] Authenticating admin request
21:06:56 │ remix │ [shopify-app/DEBUG] Validating session token
21:06:56 │ remix │ [shopify-app/DEBUG] Failed to validate session token: Failed to parse session token
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvbmV3LWRhbm9qYS5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvbmV3LWRhbm9qYS5teXNob3BpZnkuY29tIiwiYXVkIjoiMTFlNGFjMTY3NzA4OTYxNWZkYjk1Zjc0NGZlZTZiMmIiLCJzdWIiOiI0MDYyMDI5NDIxOSIsImV4cCI6MTY5NzgxNjI5OCwibmJmIjoxNjk3ODE2MjM4LCJpYXQiOjE2OTc4MTYyMzgsImp0aSI6ImIzZmQzMmQ0LTBhN2UtNGMzMC1iMjE0LWJmMWVmNDkzNmYwMSIsInNpZCI6IjQyZDExM2RkYzE2NDU0YTg0YTM5NGY1Nzc0YWNjNmJhNTMyNWEzMDk1MTg2YmE1MDQ5NmY5MDJjNGQ5MTFkNzcifQ.P0SlesRI-STPIEW-QGAsZcynrtxn7Q6DOe5FNj1Ksh0': "nbf" claim timestamp check failed
21:06:56 │ remix │ [shopify-app/DEBUG] Failed to validate session token: Failed to parse session token
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvbmV3LWRhbm9qYS5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvbmV3LWRhbm9qYS5teXNob3BpZnkuY29tIiwiYXVkIjoiMTFlNGFjMTY3NzA4OTYxNWZkYjk1Zjc0NGZlZTZiMmIiLCJzdWIiOiI0MDYyMDI5NDIxOSIsImV4cCI6MTY5NzgxNjI5OCwibmJmIjoxNjk3ODE2MjM4LCJpYXQiOjE2OTc4MTYyMzgsImp0aSI6ImIzZmQzMmQ0LTBhN2UtNGMzMC1iMjE0LWJmMWVmNDkzNmYwMSIsInNpZCI6IjQyZDExM2RkYzE2NDU0YTg0YTM5NGY1Nzc0YWNjNmJhNTMyNWEzMDk1MTg2YmE1MDQ5NmY5MDJjNGQ5MTFkNzcifQ.P0SlesRI-STPIEW-QGAsZcynrtxn7Q6DOe5FNj1Ksh0': "nbf" claim timestamp check failed
21:06:56 │ remix │ GET /app?embedded=1&hmac=e0dfa7a212d0fcebe48fed612bf046cfd8aa87fad48b6ac315f2a9c6e2497ead&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvbmV3LWRhbm9qYQ&locale=en&session=e7f5ad1d76cd55c13474c399c2b84e7d909e393cf718f7b55702a1ef3f951b1c&shop=new-danoja.myshopify.com&timestamp=1697816238 401 - - 42.761 ms`

Interestingly It says about a timestamp check failed. @horst7000 May be I have the same issue as you. But I am not sure the time I need to synchronize my laptop. I am synchronized to the real time IST. Do I need to change it to something else?

**Comment by DorWeid** [comment] 2023-11-13 09:33
> Just coming here to add, I also was bitten by this mismatching scopes issue for hours.
> 
> You have to update scopes in 3 separate locations, which is a recipe for problems like this
> 
> At a bare minimum there should be a dev log somewhere in the code that warns "Expected SCOPES: ___, but received SCOPES: ___, please check your runtime variables are up to date with the App config, and synced with your Shopify project"
> 
> Ideally we'd discard the need for scope management in the runtime variables. Clearly the instantiation knows what Scopes are set on Shopify, otherwise it wouldn't throw the error, so why do we need to pass in SCOPES at runtime at all?

Same here. This cost me a few good hours.

**Comment by owlyowl** [comment] 2023-11-23 01:34
I'd be interested to know what Shopify's position on handling dynamic scopes per login would be as well. Seeing as even static scopes are causing an issue.

Each install of our app has a different set of scopes depending on which features of our app our users are using.

**Comment by antoniovm** [comment] 2023-11-28 12:11
Hi everyone!

After a lot of hours messing around, finally I found this github issue that helped me to solve the problem. In my case I was setting up a testing embedded app in [fly.io](fly.io). So let me summarize what I've done to finally make it work.

- Uninstall development app
- Reinstall app in assigned production test shop
- Make sure that `shopify.app.toml`, `fly.toml` and `.env` variables have exact same `SCOPES`
- Run `pnpm shopify app config link` to connect remote config with local shopify.app.toml file
- Run `pnpm shopify app config push` upload scopes to remote app configuration
- Deploy app running `fly deploy`

Good luck!

**Comment by narenkram** [comment] 2024-03-24 06:17
I have no idea why but updating SCOPES works. just added a unnecessary scope I'm not going to use

**Comment by sle-c** [comment] 2024-09-18 15:23
this issue should now be resolved with https://github.com/Shopify/shopify-app-js/pull/791

**Closed by sle-c** 2024-09-18 15:23 UTC
