### ISSUE TITLE
 npm init @shopify/app@latest fails with node-gyp error with @parcel/watcher

### ISSUE THREAD

**Issue by matthaake** [Shopify/shopify-app-template-remix#549] opened 2024-02-10 00:03 UTC
# Issue summary

Cannot create a new shopify app with  npm init @shopify/app@latest  

- `@shopify/shopify-app-remix` version: latest
- Node version: v21.6.1
- Operating system: Mac Ventura 13.0

```
Command failed with exit code 1: npm install
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm ERR! code 1
npm ERR! path /private/var/folders/zw/06zxdtg56z79_17fmpb81z6m0000gn/T/fd53b47bdf2b16176328711748b4718e/app/node_modules/@parcel/watcher
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.6 found at "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/Users/matthaake/.nvm/versions/node/v21.6.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/private/var/folders/zw/06zxdtg56z79_17fmpb81z6m0000gn/T/fd53b47bdf2b16176328711748b4718e/app/node_modules/@parcel/watcher/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/matthaake/.nvm/versions/node/v21.6.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/Users/matthaake/Library/Caches/node-gyp/21.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/Users/matthaake/Library/Caches/node-gyp/21.6.1',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/Users/matthaake/.nvm/versions/node/v21.6.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/Users/matthaake/Library/Caches/node-gyp/21.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/private/var/folders/zw/06zxdtg56z79_17fmpb81z6m0000gn/T/fd53b47bdf2b16176328711748b4718e/app/node_modules/@parcel/watcher',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /private/var/folders/zw/06zxdtg56z79_17fmpb81z6m0000gn/T/fd53b47bdf2b16176328711748b4718e/app/node_modules/@parcel/watcher) while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/Users/matthaake/.nvm/versions/node/v21.6.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:519:28)
npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/Users/matthaake/.nvm/versions/node/v21.6.1/bin/node" "/Users/matthaake/.nvm/versions/node/v21.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /private/var/folders/zw/06zxdtg56z79_17fmpb81z6m0000gn/T/fd53b47bdf2b16176328711748b4718e/app/node_modules/@parcel/watcher
npm ERR! gyp ERR! node -v v21.6.1
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
```

## Steps to reproduce the problem

1.  npm init @shopify/app@latest

**Comment by lizkenyon** [comment] 2024-02-14 20:03
Hi there 👋 

I am going to close this as a duplicate of #543 

All updates regarding this issue will happen there, thanks!

**Closed by lizkenyon** 2024-02-14 20:03 UTC
