### ISSUE TITLE
Unhandled Promise Rejection when using admin.graphql with shopify api v9 deployed to vercel

### ISSUE THREAD

**Issue by anhdd-kuro** [Shopify/shopify-app-template-remix#530] opened 2024-01-29 03:35 UTC
# Issue summary

I am currently working on a Shopify custom app built with the Remix template and deployed on Vercel. Initially, it ran smoothly with Remix version 2.5.1 and Shopify API version 8.1. However, upon updating to [Shopify API version 9](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/migrating-to-v9.md#migrating-to-v9), the application started crashing when making any API calls using admin.graphql. Below is the detailed log:

```
Unhandled Promise Rejection 
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: First parameter has member 'readable' that is not a ReadableStream.",
"reason":
{"errorType":"TypeError","errorMessage":
"First parameter has member 'readable' that is not a ReadableStream.",
"stack":["TypeError: First parameter has member 'readable' that is not a ReadableStream.","   
 at assertReadableStream (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:466:19)","    
at convertReadableWritablePair (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4038:9)","    
at ReadableStream.pipeThrough (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4122:29)","    
at fetchFinale (node:internal/deps/undici/undici:9584:56)","    
at mainFetch (node:internal/deps/undici/undici:9476:9)","    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: First parameter has member 'readable' that is not a ReadableStream.","    
at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    
at process.emit (node:events:529:35)","    
at emit (node:internal/process/promises:149:20)","    
at processPromiseRejections (node:internal/process/promises:283:27)","    
at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
```

I have created [simple reproduction](https://github.com/anhdd-kuro/test-vercel-app)
It's work fine at route `/products_2` which directly use fetch , but failed at `/products`
Maybe this is vercel's problem but I can't explain why it's work normally at local
According to the logs , it passed authenticate
 
![スクリーンショット 2024-01-29 12 28 05](https://github.com/Shopify/shopify-app-template-remix/assets/13819766/c284cdb4-b44b-4cff-a495-bce1146bdedf)

Please assist in identifying and resolving this issue. Thank you.

**Comment by lizkenyon** [comment] 2024-02-01 18:05
Hi there 👋 

We have received [other reports ](https://github.com/Shopify/shopify-app-template-remix/issues/500)that after upgrading to V9 the app no longer works when deploying to Vercel.

There has been some known issues with deploying Remix apps to Vercel because Vercel uses their own fork of the Remix library. 

We are going to take a look into this to try to determine where the bug actually lies. Your repo with for reproduction will come in very helpful for that! Thanks! 

I am going to close this ticket, and we will be providing updates on #500

**Closed by lizkenyon** 2024-02-01 18:05 UTC
