### ISSUE TITLE
Client side JavaScript does not work on app proxy pages

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/shopify-app-template-remix#436] opened 2023-11-24 22:05 UTC
# Issue summary

If I create a route in the Remix app with a basic loader and a React component to render as the page content, the page renders properly, but no client side JS works. I tried adding the Scripts component to my route, but no luck.
Perhaps the Remix app doesn't support rendering pages like this?

For example: 

```javascript
import { useLoaderData } from '@remix-run/react';
import { json } from '@remix-run/node';
import { authenticate } from '~/shopify.server';

export async function loader({ request }) {
  console.log(request.headers);
  const { admin, session, liquid } = await authenticate.public.appProxy(
    request,
  );
  
  // Mock data, would actually use queried data here
  return json({
    entries: [
      {
        id: '1',
        name: 'One',
      },
      {
        id: '2',
        name: 'Two',
      },
    ],
  });
}

export default function WishList() {
  const { entries } = useLoaderData();

  // This doesn't do anything
  function handleSubmit(event) {
    alert('test');
    event.preventDefault();
    console.log('Submit', event.currentTarget);
  }

  return (
    <div>
      <h1>Manage Accounts</h1>
      <ul>
        {entries.map(entry => (
          <li key={entry.id}>{entry.name}</li>
        ))}
      </ul>
      <h2>Add Account</h2>
      <form
        onSubmit={handleSubmit}
      >
        <div>
          <label htmlFor="id">Account ID</label>
          <input id="id" name="id" type="text" />
        </div>
        <div>
          <label htmlFor="name">Account Name</label>
          <input id="name" name="name" type="text" />
        </div>
        <button type="submit">
          Submit
        </button>
      </form>
    </div>
  );
}
```

## Expected behavior

Ideally, rendering an app proxy page in the context of the theme by setting `Content-Type: application/liquid` for the route would work. 

## Actual behavior

The page is rendered, but client side JS is not included, so it's not really useful. 

## Steps to reproduce the problem

1. Set up an app proxy
2. Navigate to one of your Remix app's routes in front end of the shop (ie. store.myshopify.com/apps/my-app/wishlist) 
3. See the html content of your route, but no JS

**Comment by nboliver-ventureweb** [comment] 2023-11-29 18:10
@paulomarg @lizkenyon Would be awesome if you could confirm whether there's a way to load client side JS on app proxy pages, as it would be quite useful for us 🙏

**Comment by owlyowl** [comment] 2023-12-02 00:30
I believe this is by design because admin blocks/links are very sandboxed

**Comment by nboliver-ventureweb** [comment] 2024-01-26 22:28
@lizkenyon Any update here?

**Comment by paulomarg** [comment] 2024-02-13 16:15
Hey, sorry for the delay in responding - currently, JS won't load in proxies because remix will attempt to load the files from `/build` which won't work going through the proxy.

I'm looking into a way of forcing the URL in those requests to the app's URL, but haven't found one yet. I believe you might be able to load javascript if you use a liquid response (using the `liquid` helper) to load the JS code you need to run.

I'll circle back if I figure out a different way to get that to work!

**Comment by matthaake** [comment] 2024-02-16 04:23
I also just ran into this issue with the /build directory not loading in the client with app proxy. I've tried a few things but no luck..

**Attempt 1**
I had the idea of changing the [publicPath](https://remix.run/docs/en/main/file-conventions/remix-config#publicpath) in the config to the absolute url of the build directory on my server (ex https://my-remix-server.com/build/) but then I get CORS errors because the requests are coming from the shopify url. I'm stuck there because I can't figure out how to configure CORS on the shopify remix server?

**Attempt 2** 
Same as above but use the absolute path of the proxy url for the build (ex. https://mystore.myshopify.com/apps/proxy-subpath/build/). This loads without cors errors but then I get hydration errors

`Initial URL (/myapp) does not match URL at time of hydration (/apps/proxy-subpath/myapp), reloading page...`

I'm not sure if this would still be an issue if I got around the CORS errors with attempt 1?

@paulomarg if you have any thoughts on this / if I'm just wasting my time please let me know!!

**Comment by patrick-schneider-latori** [comment] 2024-04-08 13:32
I was able to at least proxy the assets to the correct proxied app url with the help of a express server upfront, but then Remix errors with `Initial URL (/hello-world) does not match URL at time of hydration (/a/proxy/hello-world), reloading page...` and reloads forever

**Comment by paulomarg** [comment] 2024-04-08 13:44
Yes Patrick, unfortunately because of the lack of rewrite support, you'll run into that issue. Right now, you have to do 2 things:
- Make sure the proxy path you configured (`https://<my-store>.myshopify.com/apps/my-proxy`) matches your internal path (`https://<my-app>/apps/my-proxy`) so Remix doesn't consider it a rewrite
- Make sure you add a trailing slash in your browser when loading the page (`https://<my-store>.myshopify.com/apps/my-proxy/`). I've forwarded this to the Remix team, hopefully we'll find a fix for this.

**Comment by patrick-schneider-latori** [comment] 2024-04-08 15:51
Thanks for the explanation @paulomarg – let me replay your recommendation, so that all the other people here around understand what you are recommending.

Start fresh install `yarn create @shopify/app`, then configure `shopify.app.toml` and add an `app_proxy` entry with example `subpatch = "my-proxy"` and `prefix = "apps"`.

Then I go into the Remix `routes` folder and create a new file, e.g. `apps.my-proxy.hello.jsx`, then insert test content like this:

```javascript
import { authenticate } from "../shopify.server";
import { useEffect } from "react";

export const loader = async ({ request }) => {
  await authenticate.public.appProxy(request);

  return null;
};

export default function App() {
  useEffect(() => {
    console.log('it works');
  }, []);

  return (
    <div>
      hello my-proxy
    </div>
  );
}
```

The `useEffect` in this example is used to see if the hydration works.

When I now head to `https://<my-store>.myshopify.com/apps/my-proxy/hello` I receive a 404, which is ok, because originally it normally uses the `hello.jsx` route file of Remix.

So I need now to tell the dev server to take this url and forward it also to the correct Remix file. So I open now `vite.config.js` and insert the following into the `server` block of my `defineConfig` function:

```
base: process.env.SHOPIFY_APP_URL,
server: {
  proxy: {
    '/hello': {
      target: process.env.SHOPIFY_APP_URL,
      changeOrigin: true,
      rewrite: (path) => {
        return path.replace(/^\/hello/, 'apps/my-proxy/hello')
      },
    },
  },
},
```

When I now head to `https://<my-store>.myshopify.com/apps/my-proxy/hello` it shows me the following result:

![Bildschirmfoto 2024-04-08 um 16 52 24](https://github.com/Shopify/shopify-app-template-remix/assets/44019982/96a64099-bfa0-4b2a-a04f-88e395ce46e4)

So I can check this as solved.

Now I try to do the same on production mode. Let's assume the production deployment will resolve on the domain "https://example.ngrok.io".

I update my urls on the `shopify.app.toml` (application_url, redirect_urls and app_proxy url), deploy the new config to my Shopify App, then I use `yarn shopify app env show` to get the current credentials of my Shopify app, open the `.env` file and copy them over, additionally I also enter `SHOPIFY_APP_URL="https://example.ngrok.io"` – then I trigger the new build with `yarn build && yarn start`.

I install the Shopify app in my production store, opening the app also in the Shopify dashboard to get a fresh offline token in the database.

Then I reopen the endpoint again on `https://<my-production-store-domain>/apps/my-proxy/hello` and whops – I got a 404. Of course, because the proxy settings are only valid for the development server.

So I install Express and create a new server.js entry file (using the official example from https://github.com/remix-run/remix/blob/main/templates/express/server.js) and tweaking it a little bit so that I get the following result:

```javascript
import { createRequestHandler } from "@remix-run/express";
import { installGlobals } from "@remix-run/node";
import express from "express";
import { createProxyMiddleware } from 'http-proxy-middleware';
import cors from "cors";

installGlobals();

const viteDevServer =
  process.env.NODE_ENV === "production"
    ? undefined
    : await import("vite").then((vite) =>
        vite.createServer({
          server: { middlewareMode: true },
        })
      );

const remixHandler = createRequestHandler({
  build: viteDevServer
    ? () => viteDevServer.ssrLoadModule("virtual:remix/server-build")
    : await import("./build/server/index.js"),
});

const app = express();

app.disable("x-powered-by");
app.use(cors());

if (viteDevServer) {
  app.use(viteDevServer.middlewares);
} else {
  app.use(
    "/assets",
    express.static(
      "build/client/assets",
      {
        immutable: true,
        maxAge: "1y",
      }
    )
  );
}

app.use(
  express.static(
    "build/client", { 
      maxAge: "1h"
    }
  )
);

app.use(
  '/hello/',
  createProxyMiddleware({
    target: process.env.SHOPIFY_APP_URL + '/apps/my-proxy/hello',
    changeOrigin: true,
  }),
);

app.all("*", remixHandler);

const port = process.env.PORT || 3000;
app.listen(port, () =>
  console.log(`Express server listening at http://localhost:${port}`)
);
```

I also adjust my start script in `package.json` to

```
"start": "npm run setup && cross-env NODE_ENV=production node ./server.js"
```

And the `vite.config.js` also needs an update:

```
base: "https://example.ngrok.io/",
build: {
  assetsDir: "apps/proxy/assets",
}
```

I found out, that the environment variable `process.env.SHOPIFY_APP_URL` is set to undefined, although defined in the `.env` file. The build then reverts back to "/", which makes the proxy useless here.

The direction of the assets also has to be changed, so that the proxy can also take care about them on request.

And here is the result:

![Bildschirmfoto 2024-04-08 um 17 45 54](https://github.com/Shopify/shopify-app-template-remix/assets/44019982/467d85b6-d4d1-4d38-a0b6-db49d37d6353)

This took my now more than three full days of work to get somehow working.

What a waste of time for something which should normally be handled by Remix/Shopify automatically.

Hopefully this information helps a lot more people around here to get this app proxy working.

**Comment by patrick-schneider-latori** [comment] 2024-04-08 22:15
I would like to add one thing here. You can adjust the `createProxyMiddleware` in the Express server to a more generic use of urls, if you are using more than one specific path:

```javascript
app.use(
  createProxyMiddleware({
    target: process.env.SHOPIFY_APP_URL,
    changeOrigin: true,
    pathFilter: '/hello/',
    pathRewrite: function (path, req) { 
      return path.replace('/hello/', '/apps/my-proxy/hello/')
    }
  }),
);
```

So any of the following urls are possible:

```
https://<my-production-store-domain>/apps/my-proxy/hello/
-> apps.my-proxy.hello.jsx
https://<my-production-store-domain>/apps/my-proxy/hello/world/
-> apps.my-proxy.hello.world.jsx
https://<my-production-store-domain>/apps/my-proxy/hello/world/123/
-> apps.my-proxy.hello.world.$id.jsx
```

**Closed** 2024-04-17 17:00 UTC

**Comment by coffeeappsshopify** [comment] 2024-04-20 15:44
> I would like to add one thing here. You can adjust the `createProxyMiddleware` in the Express server to a more generic use of urls, if you are using more than one specific path:
> 
> ```js
> app.use(
>   createProxyMiddleware({
>     target: process.env.SHOPIFY_APP_URL,
>     changeOrigin: true,
>     pathFilter: '/hello/',
>     pathRewrite: function (path, req) { 
>       return path.replace('/hello/', '/apps/my-proxy/hello/')
>     }
>   }),
> );
> ```
> 
> So any of the following urls are possible:
> 
> ```
> https://<my-production-store-domain>/apps/my-proxy/hello/
> needs Remix route file -> apps.my-proxy.hello.jsx
> 
> https://<my-production-store-domain>/apps/my-proxy/hello/world/
> needs Remix route file -> apps.my-proxy.hello.world.jsx
> 
> https://<my-production-store-domain>/apps/my-proxy/hello/world/123/
> needs Remix route file -> apps.my-proxy.hello.world.$id.jsx
> ```

I'm looking for this for a long time, thanks.
But, do you know how to use proxy app with full page render inside template using liquid content-type pr something?

**Comment by matthaake** [comment] 2024-05-10 20:00
> That being said, we've also added some components specifically for app proxies (see [`AppProxyProvider`](https://shopify.dev/docs/api/shopify-app-remix/v2/entrypoints/appproxyprovider)) which can be used in the plain app template, as long as you follow the rules I mentioned above (the URL path needs to match and it needs a trailing slash for the first request).

@paulomarg I tested this with a very simple reactive page, but it does not work because there are still cors errors loading the javascript files. The page renders, but I cannot get any reactivity.

```
import {authenticate} from '~/shopify.server';
import {AppProxyProvider} from '@shopify/shopify-app-remix/react';
import { LoaderFunctionArgs, json } from '@remix-run/node';
import { Scripts, useLoaderData } from '@remix-run/react';
import { useState } from 'react';

export async function loader({ request }: LoaderFunctionArgs) {
  await authenticate.public.appProxy(request);

  return json({ appUrl: process.env.SHOPIFY_APP_URL! });
}

export default function App() {
  const { appUrl } = useLoaderData<typeof loader>();
  const [count, setCount] = useState(0);

  return (
    <html>
      <body>
        <AppProxyProvider appUrl={appUrl}>
          <div>
            <p>You clicked {count} times</p>
            <button onClick={() => setCount(count + 1)}>
              Click me
            </button>
          </div>
        </AppProxyProvider>

        <Scripts />
      </body>
    </html>
  );
}
```

In the console I get 
`Access to script at 'https://stock-panama-fossil-baths.trycloudflare.com/build/_shared/chunk-BOXFZXVX.js' from origin 'https://<mystore>.myshopify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Is it possible to add CORS headers from the server that comes out of the box, or do we still need to set up a custom server even with the `AppProxyProvider`?

**Comment by paulomarg** [comment] 2024-05-15 13:29
I added your route to a brand new app and pointed a proxy to it, and I didn't get any such errors 🤔 

- What browser did you use?
- Did you point your browser to `https://<shop>/<path-to-proxy>/`?

For me, I could simplify that page to

```ts
import { authenticate } from "~/shopify.server";
import { AppProxyProvider } from "@shopify/shopify-app-remix/react";
import type { LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import { useState } from "react";

export async function loader({ request }: LoaderFunctionArgs) {
  await authenticate.public.appProxy(request);

  return json({ appUrl: process.env.SHOPIFY_APP_URL! });
}

export default function App() {
  const { appUrl } = useLoaderData<typeof loader>();
  const [count, setCount] = useState(0);

  return (
    <AppProxyProvider appUrl={appUrl}>
      <div>
        <p>You clicked {count} times</p>
        <button onClick={() => setCount(count + 1)}>Click me</button>
      </div>
    </AppProxyProvider>
  );
}
```

and it still worked.

**Comment by stigvanbrabant** [comment] 2024-11-27 12:58
@paulomarg I can get it to work for assets, but javascript is still not working.. I'm am returning the page with content type application/liquid, maybe that makes a difference?

This is my current code:
```typescript
export const loader = async () => {
  return {
    appUrl: process.env.SHOPIFY_APP_URL || '',
  };
}

export default function Index() {
  const { appUrl } = useLoaderData<typeof loader>();
  const [count, setCount] = useState(0);

  return (
    <AppProxyProvider appUrl={appUrl}>
      <div>
        <img src="/logo-dark.png" alt="..." />
        <p>You clicked {count} times</p>
        <button onClick={() => setCount(count + 1)}>Click me</button>
      </div>
    </AppProxyProvider>
  );
}
``` 

Where the image is being loaded correctly but the button click is doing nothing.

**Comment by tberry30** [comment] 2024-12-02 19:51
@paulomarg I'm in a similar situation as well.

I have set `responseHeaders.set("Content-Type", "application/liquid");` in `entry.server.jsx` so that it renders within the shop's theme, according to this [documentation](https://shopify.dev/docs/apps/build/online-store/display-dynamic-data#liquid-response).

However, when I add `base: process.env.SHOPIFY_APP_URL || ""` to `vite.config.ts` the javascript starts to work as expected, but the response no longer renders in the theme.

Any ideas on how we can get a proxy response to render within a theme with javascript?

**Comment by whiteshark209** [comment] 2025-06-07 08:47
Fully Hydrate a Shopify Remix App Proxy Route

Follow these steps to ensure a Shopify Remix route served via an App Proxy fully hydrates (client JS/CSS load correctly) without errors:
1. Scaffold the Shopify Remix App Template
Begin with Shopify’s official Remix app template. Use the Shopify CLI (or Yarn) to create the project. For example:
```
npm init @shopify/app@latest
# or
yarn create @shopify/app
```
Choose the Remix framework when prompted [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix#:~:text=guide%5D%28https%3A%2F%2Fshopify.dev%2Fdocs%2Fapps%2Fgetting,save%20%40shopify%2Fshopify).

This initializes a Remix app with Shopify auth, Polaris UI, and a default shopify.app.toml. 
After scaffolding, install dependencies and set up your .env with credentials (e.g. SHOPIFY_API_KEY, SHOPIFY_API_SECRET, SCOPES, etc.).
The CLI will show you these with yarn shopify app env show. You should also define SHOPIFY_APP_URL in .env to the URL where your app is running (e.g. your ngrok or tunnel address).

2. Configure the Shopify App Proxy
In shopify.app.toml, enable the App Proxy by adding an [app_proxy] block. Specify the full app URL, a prefix (one of a, apps, community, or tools), and a subpath. For example, to proxy under /apps/my-proxy, add:
```
[app_proxy]
url = "https://example.ngrok.io"
prefix = "apps"
subpath = "my-proxy"
```

This tells Shopify to send requests from https://<shop>.myshopify.com/apps/my-proxy/* to your app's server. (After editing shopify.app.toml, run shopify app deploy to push these settings
[shopify.dev](https://shopify.dev/docs/apps/build/cli-for-apps/app-configuration#:~:text=,where%20the%20app%20proxy%20is).)

> Note: The combination of prefix and subpath determines the proxy path in the merchant’s store URL
> [shopify.dev](https://shopify.dev/docs/apps/build/cli-for-apps/app-configuration#:~:text=,where%20the%20app%20proxy%20is). In the above example, the shop URL /apps/my-proxy/... will reach your app.

3. Name Your Remix Route to Match the Proxy Path
Because Remix does not support URL rewriting, the route in your app must match the proxy path exactly, and you must include a trailing slash when accessing it [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=AppProxyProvider%20Sets%20up%20a%20page,end%20in%20a%20trailing%20slash). This avoids the “rewrite” errors and hydration mismatch. For example, to handle /apps/my-proxy/hello/, create a route file:

```
app/routes/apps.my-proxy.hello.jsx
```

This filename corresponds to the path /apps/my-proxy/hello. Note the period separators for folders in Remix (so apps.my-proxy.hello.jsx maps to /apps/my-proxy/hello). In the route’s loader, authenticate the proxy request signature and return any needed data:

```
// app/routes/apps.my-proxy.hello.jsx

import { authenticate } from "~/shopify.server";
import { useEffect } from "react";

export const loader = async ({ request }) => {
  // Verify App Proxy signature
  await authenticate.public.appProxy(request);
  return null;
};

export default function HelloProxyPage() {
  useEffect(() => {
    console.log('it works');
  }, []);

  return (
    <div>
      <h1>Hello from /apps/my-proxy/hello/</h1>
      {/* More client-side logic here */}
    </div>
  );
}
```

In this example, the useEffect with console.log('it works') lets you confirm hydration on the client (the message should appear in the browser console)
github.com
. Important: Always append a trailing slash when navigating to the proxy URL (e.g. https://<shop>.myshopify.com/apps/my-proxy/hello/). Shopify’s proxy will redirect to add the slash if missing. This ensures the URL in the browser matches the server-rendered path exactly
[shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=AppProxyProvider%20Sets%20up%20a%20page,end%20in%20a%20trailing%20slash) [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=,find%20a%20fix%20for%20this), preventing the Remix hydration error “Initial URL ... does not match URL at time of hydration”.

4. Wrap Content with AppProxyProvider
Shopify provides an AppProxyProvider component that ensures assets load correctly behind the proxy [shopify.dev](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=,find%20a%20fix%20for%20this). In your proxy route component, wrap the content with AppProxyProvider, passing the app’s base URL (usually from process.env.SHOPIFY_APP_URL via the loader). For example:

```
// app/routes/apps.my-proxy.hello.jsx (continued)

import { useLoaderData } from "@remix-run/react";
import { AppProxyProvider } from "@shopify/shopify-app-remix/react";

export const loader = async ({ request }) => {
  await authenticate.public.appProxy(request);
  return { appUrl: process.env.SHOPIFY_APP_URL };
};

export default function HelloProxyPage() {
  const { appUrl } = useLoaderData();
  return (
    <AppProxyProvider appUrl={appUrl}>
      {/* ... your content ... */}
      <h1>Hello from Proxy!</h1>
      <p>This page is behind the app proxy.</p>
    </AppProxyProvider>
  );
}
```

The AppProxyProvider (v3) automatically sets up the page so that JavaScript and CSS assets are loaded from the app’s domain, even though the page is rendered through Shopify’s domain [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=AppProxyProvider%20Sets%20up%20a%20page,end%20in%20a%20trailing%20slash). Remember to include authenticate.public.appProxy(request) in the loader so that Shopify’s signed proxy requests are validated [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=%28e.g.%2C%20%60https%3A%2F%2F%2Fapps%2Fproxy%2F%60%29.%20%60%60%60typescript%20import%20,AppProxyProviderProps).

5. Configure Vite (Dev and Prod)
Edit vite.config.ts (or .js) to adjust the asset URLs and proxies:

- Development server: Set base to the app’s full URL, and define a proxy so that a friendly path (e.g. /hello) maps to your proxied route. For example:

```
// vite.config.ts (development)
import { defineConfig } from 'vite';
export default defineConfig({
  base: process.env.SHOPIFY_APP_URL, // e.g. https://example.ngrok.io/
  server: {
    proxy: {
      // Proxy /hello to /apps/my-proxy/hello (your route)
      '/hello': {
        target: process.env.SHOPIFY_APP_URL,
        changeOrigin: true,
        rewrite: path => path.replace(/^\/hello/, '/apps/my-proxy/hello')
      },
    },
  },
});
```

- With this, when you run the dev server (yarn dev), visiting http://localhost:5173/hello will forward to https://<your-app>/apps/my-proxy/hello [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=So%20I%20need%20now%20to,function). (You would then visit the Shopify store URL which proxies to this path.)

- Production build: Set base to your app’s public URL (with trailing slash) and align assetsDir to the proxy path. For example:
```
// vite.config.ts (production)
export default defineConfig({
  base: "https://example.ngrok.io/",           // your public URL
  build: {
    assetsDir: "apps/my-proxy/assets",         // match the proxy subpath
  },
});
```

This ensures that built asset URLs (JS/CSS) include /apps/my-proxy/assets/… so Shopify will load them correctly [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=And%20the%20,an%20update). (Adjust "apps/my-proxy/assets" to match your actual prefix/subpath.)

6. Custom Express Server (server.js)
For production, run your built Remix app on a custom Node/Express server so you can serve static assets with proper CORS. Create server.js (or server.mjs) like this:

```
// server.js
import express from "express";
import { createRequestHandler } from "@remix-run/express";
import cors from "cors";

const app = express();
app.disable("x-powered-by");

// Enable CORS so Shopify’s domain can load assets
app.use(cors());

// In production, serve static files from the Remix build
app.use("/assets", express.static("build/client/assets", {
  immutable: true,
  maxAge: "1y",
}));
app.use(express.static("build/client"));

// All other requests handled by Remix
app.all("*", createRequestHandler({ build: require("./build/index.js") }));

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
```

Key points in this server:
- CORS: We call app.use(cors()) so that the browser will allow JS/CSS requests initiated from the Shopify store domain [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=server%20remix).
- Static assets: We serve the built assets under /assets (matching the assetsDir from vite.config) with long cache TTL, and the rest of build/client. This makes /apps/my-proxy/assets/... reachable.
- Remix handler: All other routes (like /apps/my-proxy/hello/) are passed to createRequestHandler which renders your pages on the server.

To start the server in production mode, use something like:
```
// package.json
{
  "scripts": {
    "build": "remix build",
    "start": "node server.js"
  }
}
```

Then run yarn build && yarn start. (If using Vite’s dev server in local development, you can conditionally apply vite.createServer({ middlewareMode: true }) in the Express app as shown in community examples – this handles HMR. But the key idea is the same: set CORS and static serving.)
7. Environment and Configuration Files
Ensure your .env and shopify.app.toml contain the correct values:

- .env – include your Shopify API keys, the SHOPIFY_APP_URL (your app’s base URL, e.g. https://example.ngrok.io), and any other standard variables. For example:

```
SHOPIFY_API_KEY=your_api_key
SHOPIFY_API_SECRET=your_api_secret
SCOPES=read_products,write_orders
SHOPIFY_APP_URL=https://example.ngrok.io
NODE_ENV=production

```
- shopify.app.toml – must match the URLs and proxy path. For example:

```
application_url = "https://example.ngrok.io"
redirect_urls = ["https://example.ngrok.io/auth/callback"]

[app_proxy]
url = "https://example.ngrok.io"
prefix = "apps"
subpath = "my-proxy"
```

When moving to production (or to a new tunnel URL), update both the .env and shopify.app.toml accordingly. Then redeploy the app settings (Shopify CLI’s deploy or the Partner Dashboard) so that Shopify knows the new URLs [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=I%20update%20my%20urls%20on,yarn%20build%20%26%26%20yarn%20start).

8. Deploying with a Tunnel (ngrok/Cloudflare)
During development, you can expose your local app to Shopify using ngrok or Cloudflare Tunnel. For example:
Start your tunnel so that your app is reachable at a public URL (e.g. https://abcd1234.ngrok.io).
Update SHOPIFY_APP_URL in .env to https://abcd1234.ngrok.io and update application_url / app_proxy.url in shopify.app.toml to the same.
Redeploy the app config (shopify app deploy).
Rebuild and start your server (yarn build && yarn start) so it serves at the new URL.
In the Shopify Partner dashboard or CLI, install or open your app on a development store (to update the offline token etc.).
Visit the proxy URL in the store, e.g. https://<your-store>.myshopify.com/apps/my-proxy/hello/.
These steps mirror the community example: they updated the shopify.app.toml and .env with the ngrok domain, then rebuilt and ran the app
github.com
. If you get a 404 at first, ensure the tunnel is running and the URLs match exactly.

9. Test and Verify Hydration
To confirm that the page fully hydrates (and client JS runs):
Open the browser console on the proxy page (e.g. /apps/my-proxy/hello/). If your useEffect runs correctly, you should see your log (like “it works”)
github.com
.
Check network requests: The JS and CSS files should be loading from your app’s domain under /apps/my-proxy/assets/.... There should be no CORS errors in the console.
No hydration errors: You should not see a “hydration failed” or URL mismatch error. If everything is set up correctly (matching paths and trailing slash), the server-rendered HTML should match the client route exactly [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=AppProxyProvider%20Sets%20up%20a%20page,end%20in%20a%20trailing%20slash) [github.com](https://github.com/Shopify/shopify-app-template-remix/issues/436#:~:text=,find%20a%20fix%20for%20this)
.
For example, in our useEffect test above, the console log proves hydration. Alternatively, you could trigger an alert() or update component state to visually confirm that React has taken over.

10. (Bonus) Using New App Proxy Components
Shopify’s @shopify/shopify-app-remix v3 includes helper components for proxies:
- AppProxyProvider (as shown) wraps your page so assets load properly [shopify.dev](https://shopify.dev/docs/api/shopify-app-remix/v3/entrypoints/appproxyprovider#:~:text=AppProxyProvider%20Sets%20up%20a%20page,end%20in%20a%20trailing%20slash).
- AppProxyLink and AppProxyForm are specialized components for links/forms inside a proxied page. They ensure navigation respects the proxy path. You can use these for routing or submitting forms within the proxy context (see Shopify’s docs for usage).
- These components make it easier to build full-featured proxy pages without breaking out of the proxy path.

By following these steps—matching route names to proxy paths, setting CORS and asset directories on the server, configuring Vite’s base paths, and wrapping your page with AppProxyProvider—you ensure that a Shopify Remix route behind an App Proxy will fully hydrate with no missing JS/CSS. The key is that the URL in the browser (Shopify store) must exactly match the route in your Remix app, and that static assets are served from the same origin your app expects. If correctly set up, your client-side code (hooks, event handlers, etc.) will run as normal under the proxy, just as if you were visiting the app directly.
